= Installing Doxa
Author Nicolas Piganeau
:prewrap!:
:toc:
:sectnums:

== Introduction
Since Doxa is a modular ERP at compile time, it is only distributed as source
code. The following instructions will guide you through the process of
downloading the source code, setting up your configuration and compile Doxa.

== Prerequisites

=== Install Go
First of all, you need to install the Go SDK. Follow the instructions on the
Go website to install on your platform: https://golang.org/dl/ .

**Doxa requires Go version 1.9 at least, but Go 1.10 is highly recommended**

Then setup your Go workspace and define your `$GOPATH` environment variable as
described here: https://golang.org/doc/code.html#Workspaces

NOTE: It is assumed in the document that you added `$GOPATH/bin` to your
`$PATH`.

=== Install lessc

Doxa needs the less compiler `lessc` to be installed.

If you have `npm`, you can use:

```
$ npm install -g less
```

On Debian/Ubuntu you can alternately run:

```
$ sudo apt-get install node-less
```

== Download

=== Download Doxa
Doxa uses the standard go toolchain. Download Doxa with the following command:

[source,shell]
----
go get github.com/labneco/doxa
----

This will download doxa and its dependencies in your workspace and compile the
`doxa` command.

=== Download Doxa modules
Doxa modules are distributed as Go packages. They can be downloaded with
`go get` too. For instance, to get the official addons:

[source,shell]
----
go get -d github.com/labneco/doxa-ui
go get -d github.com/labneco/doxa-addons
----

NOTE: Discard any message about no buildable Go code

== Create a project
You need to create a project directory to run a Doxa server. Your project will hold
your configuration file and startup files that will be generated by Doxa.

=== Download Demo Project
If you want to evaluate Doxa, you can download the `doxa-demo` project.

[source,shell]
----
go get github.com/labneco/doxa-demo
----

=== Creating a custom project
To create a custom project, create a new folder with a `doxa.toml` file inside.
Edit this configuration file to look like this (adapt as needed):

[source,toml]
----
Modules = [
    "github.com/labneco/doxa-addons/sale"
]
LogStdout = true
#LogFile = ""
#LogLevel = "info"
#Debug = false
#DataDir = ""

[DB]
#Driver = "postgres"
#Host = "/var/run/postgresql"
#Port = 5432
#User = ""
#Password = ""
#Name = "Doxa"

[Server]
#Languages = ["fr"]
#Interface = ""
#Port = 8080
----

[NOTE]
====
Alternatively, Doxa can read its configuration from environment variables starting with `DOXA_` followed by an upper cased config setting.

For example:

- `DOXA_MODULES` -> `Modules`
- `DOXA_DB_HOST` -> `DB.Host`
====

=== Generate Doxa

This step will generate some source code that depends on the modules you
selected in the previous step. It must be performed after each modification
of the configuration from inside the project directory.

[source,shell]
----
cd <projectDir>
doxa generate
----

Type `doxa help generate` for the list of available options:

[source,shell]
----
$ doxa help generate
Generate the source code of the pool package which includes the definition of all the models.
Additionally, this command creates the startup file of the project.
This command must be rerun after each source code modification, including module import.

  projectDir: the directory in which to find the go package that imports all the modules we want.
              If not set, projectDir defaults to the current directory

Usage:
  doxa generate [projectDir] [flags]

Flags:
      --empty         Generate an empty pool package. When set projectDir is ignored.
  -t, --test string   Generate pool for testing the module in the given source directory. When set projectDir is ignored.

Global Flags:
  -c, --config string        Alternate configuration file to read. Defaults to $HOME/.doxa/
      --db-driver string     Database driver to use (default "postgres")
      --db-host string       The database host to connect to. Values that start with / are for unix domain sockets directory (default "/var/run/postgresql")
      --db-name string       Database name (default "doxa")
      --db-password string   Database password. Leave empty when connecting through socket
      --db-port string       Database port. Value is ignored if db-host is not set (default "5432")
      --db-user string       Database user. Defaults to current user
      --debug                Enable server debug mode for development
  -l, --log-file string      File to which the log will be written
  -L, --log-level string     Log level. Should be one of 'debug', 'info', 'warn', 'error' or 'crit' (default "info")
  -o, --log-stdout           Enable stdout logging. Use for development or debugging.
----

IMPORTANT: Under Windows, `doxa generate` must be run as admin.

== Synchronise database

=== Setup Postgresql

For now Doxa only supports Postgresql. Here is the quick setup for evaluating
Doxa. Please refer to Postgresql documentation for finer setup.

==== Create a postgres user
On Linux, use your distribution's package, then create a postgres user named
like your login:

[source,shell]
----
$ sudo su - postgres -c "createuser -s $USER"
----
Because the role login is the same as your unix login unix sockets can be use
without a password.

==== Create a doxa database
[source,shell]
----
$ createdb doxa
----

=== Synchronise database schema with models

This step will synchronise the database with the models defined.

[source,shell]
----
cd <projectDir>
doxa updatedb -o
----

Type `doxa help updatedb` for the list of available options:

[source,shell]
----
$ doxa help updatedb
Synchronize the database schema with the models definitions.

Usage:
  doxa updatedb [flags]

Global Flags:
  -c, --config string        Alternate configuration file to read. Defaults to $HOME/.doxa/
      --db-driver string     Database driver to use (default "postgres")
      --db-host string       The database host to connect to. Values that start with / are for unix domain sockets directory (default "/var/run/postgresql")
      --db-name string       Database name (default "doxa")
      --db-password string   Database password. Leave empty when connecting through socket
      --db-port string       Database port. Value is ignored if db-host is not set (default "5432")
      --db-user string       Database user. Defaults to current user
      --debug                Enable server debug mode for development
  -l, --log-file string      File to which the log will be written
  -L, --log-level string     Log level. Should be one of 'debug', 'info', 'warn', 'error' or 'crit' (default "info")
  -o, --log-stdout           Enable stdout logging. Use for development or debugging.
----

== Running Doxa

Doxa is launched by the `doxa server` command from inside the project directory.

[source,shell]
----
cd <projectDir>
doxa server -o
----

Type `doxa help server` to get the list of available options:

[source,shell]
----
$ doxa help server
Start the Doxa server of the project in 'projectDir'.
If projectDir is omitted, defaults to the current directory.

Usage:
  doxa server [projectDir] [flags]

Flags:
  -i, --interface string   Interface on which the server should listen. Empty string is all interfaces
  -p, --port string        Port on which the server should listen. (default "8080")

Global Flags:
  -c, --config string        Alternate configuration file to read. Defaults to $HOME/.doxa/
      --db-driver string     Database driver to use (default "postgres")
      --db-host string       The database host to connect to. Values that start with / are for unix domain sockets directory (default "/var/run/postgresql")
      --db-name string       Database name (default "doxa")
      --db-password string   Database password. Leave empty when connecting through socket
      --db-port string       Database port. Value is ignored if db-host is not set (default "5432")
      --db-user string       Database user. Defaults to current user
      --debug                Enable server debug mode for development
  -l, --log-file string      File to which the log will be written
  -L, --log-level string     Log level. Should be one of 'debug', 'info', 'warn', 'error' or 'crit' (default "info")
  -o, --log-stdout           Enable stdout logging. Use for development or debugging.
----

You can now access the Doxa server at http://localhost:8080

Default credentials are :

- Login: `admin`
- Password: `admin`
