// Copyright 2017 NDP Systèmes. All Rights Reserved.
// See LICENSE file for full licensing details.

package cmd

import (
	"text/template"

	"github.com/doxa-erp/doxa/doxa/models"
	"github.com/doxa-erp/doxa/doxa/server"
	"github.com/spf13/cobra"
	"github.com/spf13/viper"
)

const updateDBFileName string = "updatedb.go"

var updateDBCmd = &cobra.Command{
	Use:   "updatedb",
	Short: "Update the database schema",
	Long:  `Synchronize the database schema with the models definitions.`,
	Run: func(cmd *cobra.Command, args []string) {
		projectDir := "."
		if len(args) > 0 {
			projectDir = args[0]
		}
		generateAndRunFile(projectDir, updateDBFileName, updateDBTemplate)
	},
}

// UpdateDB updates the database schema. It is meant to be called from
// a project start file which imports all the project's module.
func UpdateDB(config map[string]interface{}) {
	setupConfig(config)
	setupLogger()
	setupDebug()
	server.PreInit()
	connectToDB()
	models.BootStrap()
	models.SyncDatabase()
	server.LoadDataRecords()
	if viper.GetBool("Demo") {
		log.Info("Demo mode detected: loading demo data")
		server.LoadDemoRecords()
	}
	log.Info("Database updated successfully")
}

func init() {
	DoxaCmd.AddCommand(updateDBCmd)
}

var updateDBTemplate = template.Must(template.New("").Parse(`
// This file is autogenerated by doxa-server
// DO NOT MODIFY THIS FILE - ANY CHANGES WILL BE OVERWRITTEN

package main

import (
	"github.com/doxa-erp/doxa/cmd"
{{ range .Imports }}	_ "{{ . }}"
{{ end }}
)

func main() {
	cmd.UpdateDB({{ .Config }})
}
`))
