// Copyright 2017 NDP Systèmes. All Rights Reserved.
// See LICENSE file for full licensing details.

package generate

import (
	"fmt"
	"go/build"

	"github.com/doxa-erp/doxa/doxa/tools/logging"
)

const (
	// DoxaPath is the go import path of the base doxa package
	DoxaPath = "github.com/doxa-erp/doxa"
	// ModelsPath is the go import path of the doxa/models package
	ModelsPath = "github.com/doxa-erp/doxa/doxa/models"
	// DatesPath is the go import path of the doxa/models/types/dates package
	DatesPath = "github.com/doxa-erp/doxa/doxa/models/types/dates"
	// PoolPath is the go import path of the autogenerated pool package
	PoolPath = "github.com/doxa-erp/doxa/pool"
	// PoolModelPackage is the name of the pool package with model data
	PoolModelPackage = "h"
	// PoolQueryPackage is the name of the pool package with query dat
	PoolQueryPackage = "q"
)

var (
	log *logging.Logger
	// DoxaDir is the directory of the base doxa package
	DoxaDir string
	// ModelMixins are the names of the mixins declared in the models package
	ModelMixins map[string]bool = map[string]bool{
		"CommonMixin":    true,
		"BaseMixin":      true,
		"ModelMixin":     true,
		"TransientMixin": true,
	}
)

func init() {
	log = logging.GetLogger("tools/generate")
	doxaPack, err := build.Import(DoxaPath, ".", build.FindOnly)
	if err != nil {
		panic(fmt.Errorf("Error while getting Doxa root path: %s", err))
	}
	DoxaDir = doxaPack.Dir
}
